# Generated by Django 4.0.3 on 2022-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_featured_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shoe_category',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
