# Generated by Django 4.0.3 on 2022-04-10 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_shoe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='shoe_category',
        ),
        migrations.AddField(
            model_name='project',
            name='shoe_category',
            field=models.ManyToManyField(blank=True, to='projects.category'),
        ),
    ]
