# Generated by Django 4.0.3 on 2022-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_colour_size_project_shoe_colour_project_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
