# Generated by Django 4.0.3 on 2022-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shoe_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stock_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
