# Generated by Django 4.0.3 on 2022-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_customer_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shoe_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
