# Generated by Django 4.0.3 on 2022-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_shoe_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shoe_size',
        ),
        migrations.AddField(
            model_name='project',
            name='shoe_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
