# Generated by Django 4.0.3 on 2022-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_value',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
