# Generated by Django 4.0.3 on 2022-04-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_basket_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_value',
            new_name='basket_value',
        ),
    ]
