# Generated by Django 4.0.3 on 2022-04-12 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_total_value_basket_basket_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shoe_quantity',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='shoe_size',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='stock_quantity',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
